Example project enhancements
Iliailineya/Task_Manager pull request #1
Opened 2024-02-29 15:01 UTC by Iliailineya

2024-02-29 15:20 UTC, YeaaaaH commented on .gitignore
> +src/main/resources/app.properties
?

2024-02-29 15:22 UTC, YeaaaaH commented on src/main/java/spring/controller/ProjectRestController.java
> +        log.info("Creating project: " + project);
too many logs is also not a good practice

2024-02-29 15:26 UTC, YeaaaaH requested changes
remove redundant logging

2024-03-01 13:47 UTC, Iliailineya commented
Fixed

2024-03-08 15:50 UTC, YeaaaaH approved these changes

2024-03-11 18:03 UTC, merged